server:
  port: 9696
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server111:
      host:
      - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
      - 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true